name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: [macos-latest]
    steps:
      - name: Set up Go lastest version
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
        run: go version
        id: go
      
      - name: Run test
        run: go test ./...
